# Generated by Django 6.1.1 on 2026-09-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impactrecord_category_alter_impactproject_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impactproject',
            name='external_project_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='impactproject',
            name='source_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='impactproject',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='impactproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
