# Generated by Django 6.1.1 on 2026-09-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_impactproject_end_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='impactproject',
            constraint=models.UniqueConstraint(condition=models.Q(('source_organization__gt', ''), ('external_project_id__gt', '')), fields=('source_organization', 'external_project_id'), name='unique_source_project'),
        ),
    ]
